/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cms;

/**
 *
 * @author ifife
 */
public class ContactInfoGUI extends javax.swing.JFrame {
    
    private javax.swing.table.DefaultTableModel ContactsModel = new javax.swing.table.DefaultTableModel();

    /**
     * Creates new form ContactInfoGUI
     */
    public ContactInfoGUI() {
        initComponents();
        java.util.ArrayList<cms.ContactInfo> Contacts = new java.util.ArrayList<>();
        Contacts = cms.CMSManager.importFromDatabase();
        this.ContactTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        this.ContactsModel.addColumn("ID");
        this.ContactsModel.addColumn("First Name");
        this.ContactsModel.addColumn("Last Name");
        this.ContactsModel.addColumn("Status");
        
        String[] row = new String[4];
        
        for(cms.ContactInfo Current : Contacts){
            
            row[0] = Current.getID();
            row[1] = Current.getFirstName();
            row[2] = Current.getLastName();
            row[3] = Current.getContactStatus().toString();
            
            this.ContactsModel.addRow(row);
        }
        
        this.ContactTable.setModel(ContactsModel);
//        if(InputFile.exists() == true) {
//            System.out.println("File found.");
//            
//            try {
//                InputFileReader = new java.io.FileReader(InputFile);
//                BufferedReader = new java.io.BufferedReader(InputFileReader);
//                
//                while((Line = java.io.BufferedReader.readLine()) != null) {
//                    CurrentContact = cms.ContactInfo.toCSV();
//                
//            }
//            }
//        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ContactTable = new javax.swing.JTable();
        CreateButton = new javax.swing.JButton();
        ReadButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        EmailButton = new javax.swing.JButton();
        EventButton = new javax.swing.JButton();
        NewsletterButton = new javax.swing.JButton();
        HelpButton = new javax.swing.JButton();

        ContactTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ContactTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ContactTable);

        CreateButton.setText("Create new Contact");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        ReadButton.setText("Read new Contacts");
        ReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update Contact");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete Contact");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        EmailButton.setText("Send Email to Contact");
        EmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailButtonActionPerformed(evt);
            }
        });

        EventButton.setText("Send Event to Contact");
        EventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventButtonActionPerformed(evt);
            }
        });

        NewsletterButton.setText("Send Newsletter to Contact");
        NewsletterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewsletterButtonActionPerformed(evt);
            }
        });

        HelpButton.setText("Help?");
        HelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NewsletterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EventButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(HelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EmailButton)
                        .addGap(18, 18, 18)
                        .addComponent(EventButton)
                        .addGap(18, 18, 18)
                        .addComponent(NewsletterButton)
                        .addGap(18, 18, 18)
                        .addComponent(CreateButton)
                        .addGap(18, 18, 18)
                        .addComponent(ReadButton)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateButton)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(HelpButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void HelpButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog( this, "This is the Contact Info Manager, by clicking the above buttons you can manage Contacts.");
    }                                          

    private void EmailButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog( this, "This function is finished but still needs to be added to the GUI.");
    }                                           

    private void EventButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog( this, "This function is finished but still needs to be added to the GUI.");  
    }                                           

    private void NewsletterButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog( this, "This function is finished but still needs to be added to the GUI.");
    }                                                

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog( this, "This function is finished but still needs to be added to the GUI.");
    }                                            

    private void ReadButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog( this, "This function is finished but still needs to be added to the GUI.");
    }                                          

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog( this, "This function is finished but still needs to be added to the GUI.");
    }                                            

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog( this, "This function is finished but still needs to be added to the GUI.");
    }                                            

    private void ContactTableMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        // it was planned for the table to show: ID, First Name, Last Name, and Status.
        // it was also planned for double/right clicking the contact to pull open a dialog which shows all contact details.
        javax.swing.JOptionPane.showMessageDialog( this, "Coming soon. By clicking on the table you can choose which contact you wish to send an email, event, or newsletter to.");
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactInfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactInfoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable ContactTable;
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EmailButton;
    private javax.swing.JButton EventButton;
    private javax.swing.JButton HelpButton;
    private javax.swing.JButton NewsletterButton;
    private javax.swing.JButton ReadButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
